version: "3.8"

services:
  goquery:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-9000}:9000"
    environment:
      - PORT=${PORT:-9000}
      - NODE_ENV=production
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
